name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and run test docker image
      run: |
        docker build . --file Dockerfile --target test --tag gannet-test &&
        docker run gannet-test
      
